### PR TITLE
Merge upstream

### PR DESCRIPTION
**Pull request by capehill**

### CODE REVIEW

**Comment by MBeijer** [comment]
@capehill I have your changes in the AmigaPorts repo and I keep that one up to date. It should still work with AmigaOS4 + all the other platforms.

**Comment by capehill** [comment]
> 
> 
> @capehill I have your changes in the AmigaPorts repo and I keep that one up to date. It should still work with AmigaOS4 + all the other platforms.

It's possible AmigaPorts repo is missing some changes, for example this one: https://github.com/capehill/MilkyTracker/commit/7e88d907b4f2337bb03587127c040811eeb572ca

**Comment by MBeijer** [comment]
Feel free to merge that in to amigaports :) I want to support all platforms
with one repo. Easier to maintain in the long run. I always keep the
amigaports repo up to date. Currently am setting up the nightly builds
again

**Comment by MBeijer** [comment]
Perhaps merging this in here will make it easier to PR the changes to AmigaPorts?

**Pull request merged**
